import assert from "node:assert/strict";
import fs from "node:fs";

const read = (path) => fs.readFileSync(path, "utf8");
const server = read("supabase/functions/server/index.ts");
const migration = read("supabase/migrations/20261007210000_manual_payment_unique_code.sql");
const verifier = read("BATCH9_1_UNIQUE_CODE_VERIFY.sql");
const billingCore = read("supabase/migrations/20261007180000_direct_manual_payment.sql");
const api = read("src/app/lib/api.ts");
const userUi = read("src/app/components/billing-view.tsx");
const adminUi = read("src/app/components/superadmin-dashboard-view.tsx");
const tests = [];
const test = (name, fn) => tests.push([name, fn]);

test("migration persists nullable three-digit code without rewriting history", () => {
  assert.match(migration, /ADD COLUMN IF NOT EXISTS unique_code integer/);
  assert.match(migration, /unique_code IS NULL OR unique_code BETWEEN 101 AND 999/);
  assert.doesNotMatch(migration, /UPDATE\s+public\.manual_payment_requests[\s\S]{0,100}unique_code/i);
  assert.match(verifier, /failed_checks/);
});

test("active collision protection is scoped and race-safe", () => {
  assert.match(migration, /CREATE UNIQUE INDEX IF NOT EXISTS uq_manual_payment_active_unique_code/);
  assert.match(migration, /\(org_id, destination_account_id, unique_code\)/);
  assert.match(migration, /status IN \('draft', 'submitted'\)/);
  assert.match(server, /PAYMENT_UNIQUE_CODE_ATTEMPTS = 16/);
  assert.match(server, /result\.error\.code !== "23505"/);
  assert.match(server, /Kode unik pembayaran sedang penuh/);
});

test("unique code is generated by the server and client values are ignored", () => {
  const route = server.slice(server.indexOf('app.post(`${API_PREFIX}/billing/manual-requests`, requireAuth'), server.indexOf('app.post(`${API_PREFIX}/billing/manual-requests/:id/proof`'));
  assert.match(route, /unique_code: generatePaymentUniqueCode\(\)/);
  assert.match(server, /crypto\.getRandomValues/);
  assert.match(route, /const \{ tokens, destinationId, note \} = await c\.req\.json\(\)/);
  assert.doesNotMatch(route, /uniqueCode|transferAmount|approvedAmount|creditAmount/);
});

test("DTO exposes compatible amount fields and derives transfer from the canonical base", () => {
  const dto = server.slice(server.indexOf("function paymentRequestDto"), server.indexOf("function legacyPaymentRequestDto"));
  assert.match(dto, /amount_idr: baseAmount/);
  assert.match(dto, /base_amount: baseAmount/);
  assert.match(dto, /amount_requested: baseAmount/);
  assert.match(dto, /unique_code: uniqueCode/);
  assert.match(dto, /transfer_amount: baseAmount \+ \(uniqueCode \?\? 0\)/);
  assert.match(billingCore, /v_new_request\.tokens_requested/);
  assert.match(billingCore, /v_new_request\.amount_requested/);
  assert.doesNotMatch(billingCore, /unique_code|transfer_amount/);
});

test("historical rows without a code use their original amount", () => {
  assert.match(server, /const uniqueCode = Number\.isInteger/);
  assert.match(server, /: null;/);
  assert.match(server, /transfer_amount: baseAmount \+ \(uniqueCode \?\? 0\)/);
  assert.match(userUi, /item\.request\.unique_code != null/);
  assert.match(adminUi, /paymentDetail\.unique_code != null/);
});

test("modeled DTO amount aliases and historical fallback stay equivalent", () => {
  const mapDto = (amountRequested, uniqueCode) => ({
    amount_idr: amountRequested,
    base_amount: amountRequested,
    amount_requested: amountRequested,
    unique_code: uniqueCode,
    transfer_amount: amountRequested + (uniqueCode ?? 0),
  });
  const current = mapDto(100000, 237);
  assert.equal(current.amount_requested, current.base_amount);
  assert.equal(current.amount_requested, current.amount_idr);
  assert.equal(current.transfer_amount, current.amount_requested + current.unique_code);
  const historical = mapDto(100000, null);
  assert.equal(historical.transfer_amount, historical.amount_requested);
  assert.equal(historical.transfer_amount, historical.base_amount);
});

test("API exposes explicit base, code, transfer, and proof filename fields", () => {
  for (const field of ["base_amount", "unique_code", "transfer_amount", "proof_file_name"]) {
    assert.match(api, new RegExp(`\\b${field}\\b`));
  }
  assert.match(server, /proof_file_name: safePaymentProofFileName\(proof\.name\)/);
});

test("user instructions distinguish bank and static QRIS exact transfer totals", () => {
  assert.match(userUi, /Nominal Top Up/);
  assert.match(userUi, /Kode Unik/);
  assert.match(userUi, /Total Transfer/);
  assert.match(userUi, /Transfer tepat sebesar/);
  assert.match(userUi, /Masukkan nominal pembayaran tepat sebesar/);
  assert.match(userUi, /3 digit terakhir adalah kode unik pembayaran/);
  assert.match(userUi, /Kode unik tidak menambah saldo/);
});

test("admin review shows reconciliation total and separate billing credit", () => {
  assert.match(adminUi, /Nominal Top Up/);
  assert.match(adminUi, /Kode Unik/);
  assert.match(adminUi, /Total Transfer/);
  assert.match(adminUi, /Saldo yang ditambahkan/);
  assert.match(adminUi, /kode unik tidak dikreditkan/i);
  assert.match(adminUi, /Setujui & Tambahkan Saldo/);
});

test("proof upload is a visible semantic control with replace and remove", () => {
  assert.match(userUi, /Upload Bukti Pembayaran/);
  assert.match(userUi, /type="file" className="sr-only"/);
  assert.match(userUi, /<Button[^>]+onClick=\{\(\) => proofInputRef\.current\?\.click\(\)\}/);
  assert.match(userUi, /Pilih File/);
  assert.match(userUi, /Bukti pembayaran dipilih/);
  assert.match(userUi, /Ganti File/);
  assert.match(userUi, />Hapus<\/Button>/);
  assert.match(userUi, /JPG, PNG, WEBP, atau PDF • Maks\. 5 MB/);
});

test("proof selection validates locally and upload state is announced", () => {
  assert.match(userUi, /proofMimeTypes\.has\(file\.type\)/);
  assert.match(userUi, /file\.size > 5 \* 1024 \* 1024/);
  assert.match(userUi, /setMutation\("upload"\)/);
  assert.match(userUi, /role="status" aria-live="polite"/);
  assert.match(userUi, /Mengunggah bukti…/);
  assert.match(userUi, /aria-invalid=\{Boolean\(flowError\)\}/);
  assert.match(userUi, /role="alert"/);
});

test("proof backend keeps server MIME, size, state, ownership, and privacy checks", () => {
  const route = server.slice(server.indexOf('app.post(`${API_PREFIX}/billing/manual-requests/:id/proof`'), server.indexOf('app.post(`${API_PREFIX}/billing/manual-requests/:id/submit`'));
  assert.match(route, /PAYMENT_PROOF_MIME_EXTENSIONS\.get\(proof\.type\)/);
  assert.match(route, /proof\.size > PAYMENT_PROOF_MAX_BYTES/);
  assert.match(route, /\.eq\("org_id", user\.org_id\)/);
  assert.match(route, /requestRow\.status !== "draft"/);
  assert.doesNotMatch(route, /getPublicUrl|service_role/);
});

test("modeled approval excludes reconciliation code and remains exactly once", () => {
  const request = { baseAmount: 100000, uniqueCode: 237, tokens: 100, status: "submitted" };
  let balanceTokens = 0;
  const ledger = new Set();
  const approve = () => {
    if (request.status === "approved") return;
    if (!ledger.has("request-1")) {
      balanceTokens += request.tokens;
      ledger.add("request-1");
    }
    request.status = "approved";
  };
  assert.equal(request.baseAmount + request.uniqueCode, 100237);
  approve();
  approve();
  assert.equal(balanceTokens, 100);
  assert.equal(ledger.size, 1);
});

let passed = 0;
for (const [name, fn] of tests) {
  try {
    fn();
    passed += 1;
    console.log(`PASS ${name}`);
  } catch (error) {
    console.error(`FAIL ${name}`);
    throw error;
  }
}
console.log(`Batch 9.1 Payment UX Polish regression: ${passed}/${tests.length} PASS`);
